name: CI 
on:
  push:
    branches:
        - main 
jobs:
  static_analyze:
    name: Static analyze 
    runs-on: ubuntu-20.04 
    env:
      WORK_DIR: stage1/day8/base_code 
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
      working-directory: ${{env.WORK_DIR}}
    - name: Static analyze with lizard
      run: |
        make static_analyze
      working-directory: ${{env.WORK_DIR}}